### ISSUE TITLE
Aqara wireless switch (with gyroscope)

### ISSUE THREAD

**Issue by magpern** [gruijter/com.gruijter.zigbee2mqtt#1]
Any chance you could implement this? I am trying to understand the code, but I lack a lot of basic homey knowledge...
If I just understod how the driver works I would help!

The Aqara wireless switch (with gyroscope) has vibration capabilities, tilt, and drop states.
Also, the button can do four things, single, double, hold, release.

Here is some output of its capabilities:

2023-07-09T17:13:29.657Z [log] [ManagerDrivers] [Driver:device] [Device:79010b01-7b11-4328-a8b2-b183feb91b79] {
  definition: {
    description: 'Aqara vibration sensor',
    exposes: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ],
    model: 'DJT11LM',
    options: [ [Object], [Object] ],
    supports_ota: false,
    vendor: 'Xiaomi'
  },
  disabled: false,
  endpoints: {
    '1': {
      bindings: [],
      clusters: [Object],
      configured_reportings: [],
      scenes: []
    },
    '2': {
      bindings: [],
      clusters: [Object],
      configured_reportings: [],
      scenes: []
    }
  },
  friendly_name: 'VibrationSensor1',
  ieee_address: '0x00158d0003130e97',
  interview_completed: true,
  interviewing: false,
  manufacturer: 'LUMI',
  model_id: 'lumi.vibration.aq1',
  network_address: 47714,
  power_source: 'Battery',
  supported: true,
  type: 'EndDevice'
}

2023-07-09T17:13:29.659Z [log] [ManagerDrivers] [Driver:device] [Device:79010b01-7b11-4328-a8b2-b183feb91b79] [
  {
    "access": 1,
    "description": "Remaining battery in %, can take up to 24 hours before reported.",
    "name": "battery",
    "property": "battery",
    "type": "numeric",
    "unit": "%",
    "value_max": 100,
    "value_min": 0
  },
  {
    "access": 1,
    "description": "Temperature of the device",
    "name": "device_temperature",
    "property": "device_temperature",
    "type": "numeric",
    "unit": "°C"
  },
  {
    "access": 1,
    "description": "Indicates whether the device detected vibration",
    "name": "vibration",
    "property": "vibration",
    "type": "binary",
    "value_off": false,
    "value_on": true
  },
  {
    "access": 1,
    "description": "Triggered action (e.g. a button click)",
    "name": "action",
    "property": "action",
    "type": "enum",
    "values": [
      "vibration",
      "tilt",
      "drop"
    ]
  },
  {
    "access": 1,
    "name": "strength",
    "property": "strength",
    "type": "numeric"
  },
  {
    "access": 3,
    "name": "sensitivity",
    "property": "sensitivity",
    "type": "enum",
    "values": [
      "low",
      "medium",
      "high"
    ]
  },
  {
    "access": 1,
    "name": "angle_x",
    "property": "angle_x",
    "type": "numeric",
    "unit": "°",
    "value_max": 90,
    "value_min": -90
  },
  {
    "access": 1,
    "name": "angle_y",
    "property": "angle_y",
    "type": "numeric",
    "unit": "°",
    "value_max": 90,
    "value_min": -90
  },
  {
    "access": 1,
    "name": "angle_z",
    "property": "angle_z",
    "type": "numeric",
    "unit": "°",
    "value_max": 90,
    "value_min": -90
  },
  {
    "access": 1,
    "description": "Voltage of the battery in millivolts",
    "name": "voltage",
    "property": "voltage",
    "type": "numeric",
    "unit": "mV"
  },
  {
    "access": 1,
    "description": "Number of power outages",
    "name": "power_outage_count",
    "property": "power_outage_count",
    "type": "numeric"
  },
  {
    "access": 1,
    "description": "Link quality (signal strength)",
    "name": "linkquality",
    "property": "linkquality",
    "type": "numeric",
    "unit": "lqi",
    "value_max": 255,
    "value_min": 0
  }
]

**Comment by gruijter** [comment]
It has enum capabilities. Without the physical device it is very hard for me to integrate it. If you are willing to donate a device, Im willing to invest time to make it work.
If you agree pls provide a link where I can order, and donate the cost + shipping to NL:
Https://paypal.me/gruijter

**Comment by magpern** [comment]
> It has enum capabilities. Without the physical device it is very hard for me to integrate it. If you are willing to donate a device, 

That would be one way, but I think we can solve it together. I spent a few hours yesterday trying to understand how the code works, and I am getting closer to understand it now. chatGPT is also a good companion!

What I can see from the mqtt messages, many devices in the zigbee2mqtt world send an "action". Like the very common IKEA on/off switch, when you press the button to switch to ON, it sends an "action":"on". (see below)

I added a action to the capabilityMap.js and a device_action.json that shows this as Action in the app (see attached video). This will show the action in the app.

**However**, and here is the actual problem.
It is nice to see the action, but one needs a flow to handle the action. Som kind of dynamic action flow. I have not figured out how to attach custom flows to these dynamicly generated entities.
I managed to create a general flow in the app, just by adding a flow card json file. It became general for all entities, and not just for entities with the capability action.
And secondly, it didn't work. Nothing happened when the action changed.
So, can we/you introduce a flow that can trigger on devices with a custom capability, that would really solve alot of devices!

**Aqara vibration sensor**

{"action":"tilt","angle":106,"angle_x":4,"angle_x_absolute":86,"angle_y":-81,"angle_y_absolute":171,"angle_z":8,"battery":100,"device_temperature":24,"linkquality":87,"power_outage_count":14,"strength":53,"vibration":false,"voltage":3075}

**Aqara wireless switch (with gyroscope)**
{"action":"shake","battery":83,"device_temperature":30,"linkquality":182,"power":65,"power_outage_count":238,"voltage":2975}

**IKEA on/off button**
{"action":"off","battery":90,"linkquality":87,"update":{"installed_version":604241926,"latest_version":604241926,"state":"idle"}}

https://github.com/gruijter/com.gruijter.zigbee2mqtt/assets/6589760/53a69d6a-5f86-4e19-ab6c-f488a4b1b501

**Comment by magpern** [comment]
I understand! Access to physical devices makes life easier.

Yes, Action, it is kind of an enum, but also just a string.
Perhaps, just show the action just as it is (like I did), and have a "General Action Flow" that applies to any device (preferably only devices that have the capability "action").

Yes, the enum might need to be extended over time, and it might not be the best architectural design to mix all kind of action types in one, but if everything should remain as "Generic devices from zigbee2mqtt" I guess it is not doable to customize actions for each kind of device?

Then we have the IKEA TRADFRI ON/OFF switch. It reports its on/off as action. And in this perticular case, it should really be mapped to homeys onoff capability, instead of a custom action capability. This switch is a very common switch.

- Any Idea how to map a generic flow to a generic device with a specific capability (like action)?
- Any idea how to distinguish the on/off action and map it to an already existing Homey capability?

At my day job I am a developer/architect, but my experience with JS and Homey is quite limited.
(btw, HEIMAN SmokeSensor-N-3.0 works perfectly, and when there is smoke, the homey app alerts automatically)

**Comment by gruijter** [comment]
I already tried handling action enums simply as a string. But it results in very poor usability for Homey users. Not all Homey users are developers/architects (in fact most are non-technical). So handling it that way does not meet my quality standards.

**Comment by magpern** [comment]
Maybe, but don't know if I totally agree.

If the "If" is 'Action changed on [device] to [action]' (where action is a dripdown list of all available actions). It feels quite similar to all the other flows "if"-cases, where a value is smaller/bigger than.

I looked at the Aqara implementation of a device like this.
They show nothing but the battery for this device. To interact with it you create a flow. They call it 'A scene (select the action) has been activated'
Then you select the action from a list of available actions.
This is exactly the same as my thought for implementation, only difference is the action list would not be specific for this device but a general.
(Unless it is possible to distinguish between devices and assign specific enums per device).

![Screenshot_20230710_140219_Homey.jpg](https://github.com/gruijter/com.gruijter.zigbee2mqtt/assets/6589760/7cff8b82-4d67-4c7c-a61d-50f8118df891)

![Screenshot_20230710_140238_Homey.jpg](https://github.com/gruijter/com.gruijter.zigbee2mqtt/assets/6589760/a7d9cc28-7faf-4c41-b1fd-815e2c655fc5)

**Comment by gruijter** [comment]
I have some ideas on how to integrate this with best UX. I ordered a switch so I can fondle around with it. Will take some weeks to deliver. Stay tuned...

**Comment by magpern** [comment]
Great. If you want to try something out in the mean time, I can send you the mqtt messages, so you can simulate the device or be your tester or both.

It seams like many devices that can do something, use action in Z2M to publish what it should do. Even the very common ikea remote.

**Comment by gruijter** [comment]
Yes, pls send me the JSON containing the result of ```zigbee2mqtt/bridge/devices``` (at least the part defining the particular devices),
and the result of ```zigbee2mqtt/FRIENDLY_NAME```

**Comment by magpern** [comment]
I just tried this device, and it works now! Action is reported and logic card can act on it!
Great work!
