### ISSUE TITLE
Plugwise Lisa not showing occupied_heating_setpoint in Homey

### ISSUE THREAD

**Issue by rtjbevers** [gruijter/com.gruijter.zigbee2mqtt#15]
I've added a plugwise Lisa thermostat to zigbee2mqtt. Everything is working well there, but the device is not showing the occupied_heating_setpoint at all in Homey, even if I manually select the device as a thermostat.

**Comment by gruijter** [comment]
Please read the forum under 'why is my device not fully supported'
https://community.homey.app/t/app-pro-zigbee2mqtt/83214
