### ISSUE TITLE
{"state":""} sent by appInit

### ISSUE THREAD

**Issue by magpern** [gruijter/com.gruijter.zigbee2mqtt#2]
When the application starts and in the device initialization phase, it sends {"state":""}

zigbee2mqtt doesn't seam to like this. See picture.
What is the purpose? To get state?

![image](https://github.com/gruijter/com.gruijter.zigbee2mqtt/assets/6589760/92dbf2e6-bcc3-4276-a7c9-c6101adecc72)

**Comment by gruijter** [comment]
This is to get the current state of devices after Homey app start. Only works for non-battery devices. That is the message in Z2M frontend. But it is no issue. If I have time I might filter in Homey, but far from a priority.
