### ISSUE TITLE
Brige stays offline after network outage

### ISSUE THREAD

**Issue by HexVigor** [gruijter/com.gruijter.zigbee2mqtt#20]
Hello,

After a network interrupt the mqtt bridge shows offline in homey but the brige in online and running.
I see the connection made by homey in the MQTT logs.

1710923044: New connection from 192.168.200.85:42716 on port 1883.
1710923044: New client connected from 192.168.200.85:42716 as Homey_7a3356 (p2, c1, k60).

Can you assist on this?

homey diagnostic rapport: 410b7acc-766c-40d6-a841-9da52b0da17e

Many thanks
Sander

**Comment by HexVigor** [comment]
In the end, I did remove the bridge from homey and the devices. Recreated it and it works again. 

There was an issue with the broker, got it working again, tested with another MQTT client and there I did see the publications for the topic. No change in the broker status on homey. The communication did work in some way. If I did change the allow joining setting in homey, it shows up in the zigbee2MQTT log on the raspberry docker.

**Comment by gruijter** [comment]
In the log I see that the broker somehow didn't send JSON anymore, but in some other format:
```2024-03-20T08:24:04.435Z [err] [ManagerDrivers] [Driver:bridge] [Device:464f45cb-2243-4e1a-898b-6584bb616fb0] SyntaxError: Unexpected token o in JSON at position 0
    at JSON.parse (<anonymous>)
    at MqttClient.handleMessage (/app/drivers/bridge/device.js:152:24)
    at MqttClient.emit (node:events:517:28)
    at MqttClient._handlePublish (/app/node_modules/mqtt/lib/client.js:1547:12)
    at MqttClient._handlePacket (/app/node_modules/mqtt/lib/client.js:535:12)
    at work (/app/node_modules/mqtt/lib/client.js:438:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)```

But I'll close it now since you solved it.
