### ISSUE TITLE
Support for the Avatto TRV TRV07 thermostat

### ISSUE THREAD

**Issue by omare70** [gruijter/com.gruijter.zigbee2mqtt#24]
Can you add support in Zigbee2MQTT for Homey Avatto TRV TRV07 thermostat?

https://github.com/eteodun/Avatto-TRV07-TS0601-_TZE200_bvrlmajk

**Comment by gruijter** [comment]
Did you try it? What is not working?
If you need me to add something, please send me the funds to buy this device (including shipping costs to NL).
