### ISSUE TITLE
Need daily reset of Zigbee2Mqtt app

### ISSUE THREAD

**Issue by Thkos123** [gruijter/com.gruijter.zigbee2mqtt#26]
The bridge app works fine in general, Except for the fact that every day it loses connection with the homey pro at some moment and after an app restart works again for approx a day. 
The zigbee device shows a red triange and after a restart of the bridge works fine again. 
My zigbee2mqtt SW runs on a PI, connected with ethernet to my home network. My Homey has wireless Wifi connection to my home network. 
![20240527_101809000_iOS](https://github.com/gruijter/com.gruijter.zigbee2mqtt/assets/97621952/1a1aafa3-4acc-41c0-beff-e020a0579ec0)

It could of course be a network issue, but after restoring connectivity, the bridge should also be online automatically. 
I could think of workarounds like restaring the app during the night, or polling connectivity and restart the app when connectivity is lost. But that is fighting symptoms, better would be to solve the real cause. 
Any ideas if it could be an app or local issue and what would be a good solution ?

**Comment by gruijter** [comment]
Please check if the new version fixes it for you: https://community.homey.app/t/app-pro-zigbee2mqtt/83214/316
