### ISSUE TITLE
Unable to connect to my Zigbee2MQTT server

### ISSUE THREAD

**Issue by izaakhorner** [gruijter/com.gruijter.zigbee2mqtt#28]
Hi there,
I'm having trouble connecting to my 2MQTT server.
I have tried using the URL and the IP but it continues to return a timeout error or not found error.
I'm running this off a Sonoff Zigbee 3.0 Dongle Plus through Home Assistant. I can load the interface in home assistant but would like to connect everything up into Homey Pro

**Comment by gruijter** [comment]
This sounds more like a network setup issue. Try using https://mqtt-explorer.com/ to help debug your network issue. If MQTT explorer cannot connect to you MQTT server, then Homey also cannot connect to it.

For support you can ask the Homey community: https://community.homey.app/t/app-pro-zigbee2mqtt/83214
