### ISSUE TITLE
mqtt bridge goes offline after few hours in homey

### ISSUE THREAD

**Issue by djwoefgithub** [gruijter/com.gruijter.zigbee2mqtt#29]
I have this irritating issue. After adding the MQTT bridge and one light devices in homey pro (2023), the bridge goes offline after a few hours. The only way to solve this issue is to remove the bridge and add it again after which it is online again. My internal network is flat. homey has ip 192.168.0.x, the zigbee2mqtt instance has 192.168.0.y (fixt). no firewalls,  nothing. 
![Screenshot from 2024-07-30 12-07-19](https://github.com/user-attachments/assets/9bc13b63-7723-41f9-9073-ca5c74fcf54a)

**Comment by djwoefgithub** [comment]
After restarting the App in Homey the light itself is available again for a few hours but the exclamation mark remains in the zigbee2mqtt bridge.

**Comment by gruijter** [comment]
Did you check this?
https://community.homey.app/t/app-pro-zigbee2mqtt/83214/314

**Comment by gruijter** [comment]
I released a new version 2.4.3. Can you check if your problem is solved? If noet, please send an app diagnostics report and post the ID here.
