### ISSUE TITLE
Is it possible to import groups

### ISSUE THREAD

**Issue by magpern** [gruijter/com.gruijter.zigbee2mqtt#3]
I have some lights in the ceiling. It is three of them, but I want them to act as one.
In zigbee2mqtt they are grouped as a single group, and a remote control switch is bound to the group and can turn light on and off.

But in Homey, I cannot access the group, I need to individually address each member in the group. Each light is exposed to Homey, but not the group.

IKEA gateway exposes a group to homey. I don't know if it is possible to act on groups in zigbee2mqtt, but maybe?

**Comment by gruijter** [comment]
No, Im not thinking about supporting groups in Homey. Too much work for me, and I dont see a big benefit.

**Comment by magpern** [comment]
Ok. I now found out rhere is an app called Groups in Homey that can do the grouping, so wanted result is achieved.
