### ISSUE TITLE
Battery operated devices that report voltage should devide value by 1000

### ISSUE THREAD

**Issue by oh2th** [gruijter/com.gruijter.zigbee2mqtt#35]
Zigbee2MQTT exposes voltage as mV for battery operated devices. Homey devices expect unit as volts, so the exposed value should be devided by 1000.

so if the device exposes battery and voltage, then voltage is in mV

**Comment by gruijter** [comment]
Both the value and the unit are taken from z2m. An automated mapping is done for all capabilities. Making exception handlers for individual capabilities is unmaintainable.

**Comment by oh2th** [comment]
Looking at the device database at zigbee2mqtt.io, every battery that reports the voltage says:

> Voltage of the battery in millivolts. Value can be found in the published state on the voltage property. It's not possible to read (/get) or write (/set) this value. The unit of this value is mV.

**Comment by gruijter** [comment]
The unit in Homey should be whatever z2m is reporting (so mV for voltage/battery). Do you have a screenshot where this is not the case?

**Comment by oh2th** [comment]
Door/Windows sensor
![image](https://github.com/user-attachments/assets/97fd5f34-2968-4113-b0c0-eec6282619f9)

Temperature/Humidity sensor
![image](https://github.com/user-attachments/assets/8b382797-81f9-41b9-9953-c5a908226a93)

Light sensor
![image](https://github.com/user-attachments/assets/a9910c16-307e-4b9b-907f-625cdb345e91)

And zigbee2mqtt all report the same, that the unit is mV for any battery device. And that is also documented at zigbee2mqtt.io devices list how battery voltage is reported if exposed.

**Comment by gruijter** [comment]
That is weird. It should say mV. Are these homey deviced maybe added with a very old app version? What happens when you add a new device to Homey?
