### ISSUE TITLE
IKEA Fyrtur blind not registered as a blind

### ISSUE THREAD

**Issue by magpern** [gruijter/com.gruijter.zigbee2mqtt#5]
The Ikea fyrtur winfow blind is just registered as a random device.
It is not usable in Homey.

[https://www.zigbee2mqtt.io/devices/E1757.html](https://www.zigbee2mqtt.io/devices/E1757.html)

`Zigbee2MQTT:info  2023-09-19 06:18:47: MQTT publish: topic 'zigbee2mqtt/Bedroom-curtain-left', payload '{"battery":38,"linkquality":98,"position":86,"state":"OPEN","update":{"installed_version":604241937,"latest_version":604241937,"state":"idle"}}'
Zigbee2MQTT:debug 2023-09-19 06:18:48: Received Zigbee message from 'Bedroom-curtain-left', type 'attributeReport', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":19}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2023-09-19 06:18:48: MQTT publish: topic 'zigbee2mqtt/Bedroom-curtain-left', payload '{"battery":38,"linkquality":98,"position":81,"state":"OPEN","update":{"installed_version":604241937,"latest_version":604241937,"state":"idle"}}'
Zigbee2MQTT:debug 2023-09-19 06:18:49: Received Zigbee message from 'Bedroom-curtain-left', type 'attributeReport', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":25}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2023-09-19 06:18:49: MQTT publish: topic 'zigbee2mqtt/Bedroom-curtain-left', payload '{"battery":38,"linkquality":98,"position":75,"state":"OPEN","update":{"installed_version":604241937,"latest_version":604241937,"state":"idle"}}'`

`Zigbee2MQTT:debug 2023-09-19 06:19:53: Received MQTT message on 'zigbee2mqtt/Bedroom-curtain-left/set' with data '{"position":24}'
Zigbee2MQTT:debug 2023-09-19 06:19:53: Publishing 'set' 'position' to 'Bedroom-curtain-left'
Zigbee2MQTT:info  2023-09-19 06:19:54: MQTT publish: topic 'zigbee2mqtt/Bedroom-curtain-left', payload '{"battery":38,"linkquality":29,"position":24,"state":"CLOSE","update":{"installed_version":604241937,"latest_version":604241937,"state":"idle"}}'
Zigbee2MQTT:debug 2023-09-19 06:19:55: Received Zigbee message from 'Bedroom-curtain-left', type 'attributeReport', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":98}' from endpoint 1 with groupID 0`

![Screenshot_20230919_080557_Homey](https://github.com/gruijter/com.gruijter.zigbee2mqtt/assets/6589760/a6139081-3e95-4598-9333-33c118bc6da3)
![Screenshot_20230919_081736_Chrome](https://github.com/gruijter/com.gruijter.zigbee2mqtt/assets/6589760/73a57804-79a4-4afd-867e-3f6aaaa2ead9)

**Comment by gruijter** [comment]
see forum: https://community.homey.app/t/app-pro-zigbee2mqtt/83214

_But to really add a device to the Homey app, I need to have my hands on it and tinker around with it. So, if you are willing to donate the device, I am willing to put in the extra effort to integrate it. When you want to donate a device, send me the funds to buy one (including shipping to NL)._

**Comment by magpern** [comment]
Well, a Fyrtur is like 160 euro, so donation is kind of out of the question.

I was more in line if there was any information you could get to easily implement it.

You have made a fantastic app for Homey. Can't you make it an official Zigbee2mqtt app and have it maintained within the zigbee2mqtt suite?

I could try implementing it myself. I havn't studied the code in detain, but I could.

**Comment by stefanrenne** [comment]
@gruijter you can get one from marktplaats for €55, maybe @magpern and I can split the costs?

https://www.marktplaats.nl/v/huis-en-inrichting/stoffering-gordijnen-en-lamellen/m2024703836-ikea-fyrtur-verduisterende-rolgordijnen-draadloos-op-zigbee

**Comment by gruijter** [comment]
Stefan added support. I released it as version 2.1.5: https://homey.app/a/com.gruijter.zigbee2mqtt/test/
